import importlib
import inspect
import pandas as pd
import numpy as np
from typing import Dict, Any, Type
from backend.app.core.strategy.base import AbstractStrategy
from backend.app.infrastructure.data.cache import ParquetCache

class BacktestEngine:
    def __init__(self, initial_capital: float = 10000.0, slippage_pct: float = 0.05, commission_pct: float = 0.03):
        self.initial_capital = initial_capital
        self.slippage = slippage_pct / 100.0
        self.commission = commission_pct / 100.0
        self.cache = ParquetCache()

    def _load_strategy(self, strategy_name: str) -> Type[AbstractStrategy]:
        module_name = ''.join(['_'+c.lower() if c.isupper() else c for c in strategy_name]).lstrip('_')
        try:
            module = importlib.import_module(f"backend.app.strategies.{module_name}")
            for name, obj in inspect.getmembers(module, inspect.isclass):
                if name == strategy_name and issubclass(obj, AbstractStrategy) and obj is not AbstractStrategy:
                    return obj
            raise ValueError(f"Strategy class {strategy_name} not found in {module_name}.py")
        except ModuleNotFoundError:
            raise ValueError(f"Strategy file {module_name}.py not found")

    def run(self, strategy_name: str, symbol: str, resolution: str, start_ms: int, end_ms: int) -> Dict[str, Any]:
        try:
            StrategyClass = self._load_strategy(strategy_name)
            strategy_instance = StrategyClass()
        except ValueError as e:
            return {"success": False, "error": str(e)}
        
        df = self.cache.load_data(symbol, resolution)
        if df.empty:
            return {"success": False, "error": f"No cached data found for {symbol}."}
            
        df = df[(df.index >= start_ms) & (df.index <= end_ms)].copy()
        if df.empty:
            return {"success": False, "error": "No data available in the requested date range after clamping."}

        df = strategy_instance.generate_signals(df)
        if 'signal' not in df.columns:
            return {"success": False, "error": "Strategy did not return a 'signal' column."}

        # Simulation Setup
        cash = self.initial_capital
        position_size = 0.0
        entry_price = 0.0
        entry_time = None
        duration_bars = 0
        
        trade_high = 0.0
        trade_low = float('inf')
        
        trades = []
        execution_log = []
        
        equity_curve_raw = []
        timestamps_raw = []
        
        pending_action = None
        
        for index, row in df.iterrows():
            current_close = float(row['close'])
            current_open = float(row['open'])
            signal = row.get('signal')
            timestamps_raw.append(index)
            
            # Record daily equity based on current close
            current_equity = cash + (position_size * current_close)
            equity_curve_raw.append(current_equity)
            
            if position_size > 0:
                duration_bars += 1
                trade_high = max(trade_high, current_close)
                trade_low = min(trade_low, current_close)
            
            # --- T+1 EXECUTION ---
            # We execute at the OPEN of this candle based on the signal generated by the PREVIOUS candle's close
            if pending_action == "BUY" and position_size == 0:
                # Slippage & Commission on Entry
                execution_price = current_open * (1 + self.slippage)
                entry_cost = execution_price * (1 + self.commission)
                
                position_size = cash / entry_cost
                cash = 0.0
                entry_price = execution_price
                entry_time = index
                duration_bars = 0
                trade_high = current_close
                trade_low = current_close
                
            elif pending_action == "SELL" and position_size > 0:
                # Slippage & Commission on Exit
                execution_price = current_open * (1 - self.slippage)
                exit_revenue = (position_size * execution_price) * (1 - self.commission)
                
                cash = exit_revenue
                profit_loss = (exit_revenue - (position_size * entry_price)) / (position_size * entry_price)
                
                
                mae = (trade_low - entry_price) / entry_price
                mfe = (trade_high - entry_price) / entry_price
                
                trades.append(profit_loss)
                execution_log.append({
                    "entry_time": entry_time,
                    "entry_price": round(entry_price, 2),
                    "exit_time": index,
                    "exit_price": round(execution_price, 2),
                    "duration_bars": duration_bars,
                    "profit_loss_pct": round(profit_loss * 100, 2),
                    "mae_pct": round(mae * 100, 2),
                    "mfe_pct": round(mfe * 100, 2)
                })
                
                position_size = 0.0
                entry_price = 0.0
                
            # Queue signal for the NEXT candle
            pending_action = signal
                
        # Close open positions
        if position_size > 0:
            final_price = float(df.iloc[-1]['close'])
            execution_price = final_price * (1 - self.slippage)
            exit_revenue = (position_size * execution_price) * (1 - self.commission)
            cash = exit_revenue
            profit_loss = (exit_revenue - (position_size * entry_price)) / (position_size * entry_price)
            
            mae = (trade_low - entry_price) / entry_price
            mfe = (trade_high - entry_price) / entry_price
            
            trades.append(profit_loss)
            execution_log.append({
                "entry_time": entry_time,
                "entry_price": round(entry_price, 2),
                "exit_time": df.index[-1],
                "exit_price": round(execution_price, 2),
                "duration_bars": duration_bars,
                "profit_loss_pct": round(profit_loss * 100, 2),
                "mae_pct": round(mae * 100, 2),
                "mfe_pct": round(mfe * 100, 2)
            })

        # --- QUANT ANALYTICS ---
        total_return = ((cash - self.initial_capital) / self.initial_capital) * 100
        
        winning_trades = [t for t in trades if t > 0]
        losing_trades = [t for t in trades if t <= 0]
        win_rate = (len(winning_trades) / len(trades) * 100) if trades else 0.0
        
        equity_series = pd.Series(equity_curve_raw, index=timestamps_raw)
        rolling_max = equity_series.cummax()
        drawdowns = (equity_series - rolling_max) / rolling_max
        max_drawdown = drawdowns.min() * 100 if not drawdowns.empty else 0.0
        
        gross_profit = sum(winning_trades)
        gross_loss = abs(sum(losing_trades))
        profit_factor = (gross_profit / gross_loss) if gross_loss != 0 else float('inf')

        # Advanced Risk
        trade_returns = pd.Series(trades)
        sharpe_ratio = 0.0
        sortino_ratio = 0.0
        if not trade_returns.empty and trade_returns.std() != 0:
            sharpe_ratio = (trade_returns.mean() / trade_returns.std()) * np.sqrt(len(trades))
            negative_returns = trade_returns[trade_returns < 0]
            if not negative_returns.empty and negative_returns.std() != 0:
                sortino_ratio = (trade_returns.mean() / negative_returns.std()) * np.sqrt(len(trades))
                
        # CAGR (assuming timestamps in ms)
        days = (timestamps_raw[-1] - timestamps_raw[0]) / (1000 * 60 * 60 * 24) if len(timestamps_raw) > 1 else 1
        years = days / 365.25 if days > 0 else 1
        cagr = (((cash / self.initial_capital) ** (1/years)) - 1) * 100 if years > 0 and cash > 0 else 0.0
        
        calmar_ratio = (cagr / abs(max_drawdown)) if max_drawdown != 0 else float('inf')

        # VaR & CVaR (Historical 95%)
        var_95 = np.percentile(trade_returns, 5) * 100 if not trade_returns.empty else 0.0
        cvar_95 = trade_returns[trade_returns <= (var_95/100)].mean() * 100 if not trade_returns.empty and len(trade_returns[trade_returns <= (var_95/100)]) > 0 else var_95
        
        # Monte Carlo (1000 iterations)
        mc_worst_5 = 0.0
        if trades:
            mc_results = []
            for _ in range(1000):
                sim_trades = np.random.choice(trades, size=len(trades), replace=True)
                sim_eq = self.initial_capital
                for st in sim_trades:
                    sim_eq *= (1 + st)
                mc_results.append(((sim_eq - self.initial_capital) / self.initial_capital) * 100)
            mc_worst_5 = np.percentile(mc_results, 5)

        avg_win = np.mean(winning_trades) * 100 if winning_trades else 0.0
        avg_loss = np.mean(losing_trades) * 100 if losing_trades else 0.0
        expectancy = ((win_rate/100) * avg_win) + ((1 - win_rate/100) * avg_loss)
        
        avg_bars = np.mean([log["duration_bars"] for log in execution_log]) if execution_log else 0
        avg_mae = np.mean([log["mae_pct"] for log in execution_log]) if execution_log else 0
        avg_mfe = np.mean([log["mfe_pct"] for log in execution_log]) if execution_log else 0

        downsample_factor = max(1, len(equity_curve_raw) // 500)
        ui_equity_curve = [
            {"time": timestamps_raw[i], "equity": round(equity_curve_raw[i], 2), "drawdown": round(drawdowns.iloc[i] * 100, 2)}
            for i in range(0, len(equity_curve_raw), downsample_factor)
        ]

        return {
            "success": True,
            "metrics": {
                "total_return_pct": round(total_return, 2),
                "cagr_pct": round(cagr, 2),
                "win_rate_pct": round(win_rate, 2),
                "max_drawdown_pct": round(max_drawdown, 2),
                "profit_factor": round(profit_factor, 2),
                "total_trades": len(trades),
                "final_equity": round(cash, 2),
                "sharpe_ratio": round(sharpe_ratio, 2),
                "sortino_ratio": round(sortino_ratio, 2),
                "calmar_ratio": round(calmar_ratio, 2),
                "var_95_pct": round(var_95, 2),
                "cvar_95_pct": round(cvar_95, 2),
                "mc_worst_5_pct": round(mc_worst_5, 2),
                "avg_win_pct": round(avg_win, 2),
                "avg_loss_pct": round(avg_loss, 2),
                "expectancy_pct": round(expectancy, 2),
                "avg_duration_bars": round(avg_bars, 1),
                "avg_mae_pct": round(avg_mae, 2),
                "avg_mfe_pct": round(avg_mfe, 2)
            },
            "chart_data": ui_equity_curve,
            "execution_log": execution_log[-100:]
        }
