"""Initial schema

Revision ID: 7e6d109f1e92
Revises: 
Create Date: 2026-08-24 16:19:45.482965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6d109f1e92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('from_ms', sa.BigInteger(), nullable=False),
    sa.Column('to_ms', sa.BigInteger(), nullable=False),
    sa.Column('starting_capital', sa.Numeric(), nullable=False),
    sa.Column('brokerage_bps', sa.Numeric(), nullable=False),
    sa.Column('slippage_bps', sa.Numeric(), nullable=False),
    sa.Column('fill_rule', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('net_pnl', sa.Numeric(), nullable=False),
    sa.Column('return_pct', sa.Numeric(), nullable=False),
    sa.Column('ending_equity', sa.Numeric(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Numeric(), nullable=False),
    sa.Column('n_trades', sa.Integer(), nullable=False),
    sa.Column('n_wins', sa.Integer(), nullable=False),
    sa.Column('n_losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(), nullable=False),
    sa.Column('fees_paid', sa.Numeric(), nullable=False),
    sa.Column('trades_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_table('live_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('symbols_json', sa.JSON(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('started_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('last_active_ms', sa.BigInteger(), nullable=False),
    sa.Column('stopped_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('state_file', sa.String(), nullable=False),
    sa.Column('crash_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_sessions_id'), 'live_sessions', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('placed_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('updated_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('trading_symbol', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(), nullable=True),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('signal_reason', sa.String(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(), nullable=True),
    sa.Column('fees', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_live_sessions_id'), table_name='live_sessions')
    op.drop_table('live_sessions')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
